#103 Info Panel Component
JBoudou/Itero pull request #120
Opened 2021-06-16 06:54 UTC by WanJIN0415

#103

2021-06-16 09:05 UTC, Jogo27 requested changes

2021-06-21 18:23 UTC, WanJIN0415 commented
PTAL

2021-06-22 07:42 UTC, Jogo27 requested changes
Only small details remain. Please fix them before I merge this PR.

2021-06-22 07:42 UTC, Jogo27 commented on app/src/app/shared/info-panel/info-panel.component.html
> +  <ng-content *ngIf = "showInfo"></ng-content>
Please remove the spaces around this equal sign.

2021-06-22 07:42 UTC, Jogo27 commented on app/src/app/shared/info-panel/info-panel.component.html
> +  <button mat-icon-button matSuffix type="button" (click)="showInfo = !showInfo">
matSuffix is useless outside Material form fields.

2021-06-22 07:55 UTC, WanJIN0415 commented
PTAL

2021-06-22 08:50 UTC, Jogo27 approved these changes
LGTM

2021-06-22 08:55 UTC, merged