Dialogbox buttons:Modifier la disposition du bouton
JBoudou/Itero pull request #85
Opened 2021-05-28 12:30 UTC by HFaaaaa

After trying to change the text content and padding, there are still some small screens that can’t adapt. Like that:
![image](https://user-images.githubusercontent.com/72395200/119983078-f8471980-bfbf-11eb-8a10-81f274e7e7b7.png)
So I try the second proposition. Change the position of the button, change the padding of the dialog box and change the padding of the part buttons.
![image](https://user-images.githubusercontent.com/72395200/119983732-d8fcbc00-bfc0-11eb-8865-6c76421b105b.png)

2021-05-28 13:02 UTC, Jogo27 requested changes
Thank you for the PR. The idea to display the button vertically when the screen is narrow is very good!
Please take the following comments into account though, in particular the requirement that **when the screen is large** the buttons must be displayed horizontally and right-aligned. Moreover, the design has to improve:
- The margin around the bock of button is too large, in particular below.
- There must be some space between the buttons (the same space as when the buttons are displayed horizontally)

2021-05-28 13:48 UTC, HFaaaaa commented on app/src/styles.sass
> +      margin-left: 8px
Thanks for your comments!!! I will resubmit after modifying those problems.

2021-05-29 10:10 UTC, HFaaaaa commented
PTAL

2021-05-31 07:34 UTC, Jogo27 requested changes
Dialog boxes look much better now, thanks! It could be even better though if all the buttons had the same width when displayed vertically. Please also take the following comments about your code into account.

2021-05-31 07:34 UTC, Jogo27 commented on app/src/sizes.sass
> +$big-space: 45px
$small-space and $medium-space are mostly spaces between borders or lines. If the font sizes change these spaces should remain the same. But if the border widths change then these spaces may change. On the contrary, it seems to me that the space between the dialog message and the button bar must be smaller if the font size is smaller and bigger if the font is bigger. Therefore, the size of this space should be written in ex or em unit. Moreover, I'm not convinced that the exact same space should be reused throughout the application. Hence I don't think it's a good candidate for an application-wide variable.

2021-05-31 15:01 UTC, HFaaaaa commented
PTAL

2021-05-31 15:20 UTC, Jogo27 requested changes
It's almost Ok, now. In addition to the following comments could you please:
1. Remove the left margin on the buttons for them to really be aligned.
2. Give the same width to all the buttons.

2021-05-31 15:20 UTC, Jogo27 commented on app/src/app/create/leave-create.dialog.html
> +
Please remove this misleading empty line.

2021-05-31 15:20 UTC, Jogo27 commented on app/src/styles.sass
> +    display: flex
This line is useless. formactions are always flex.

2021-05-31 15:20 UTC, Jogo27 commented on app/src/styles.sass
> +    justify-content: center
This line is useless, because there is no external constraint on the height of the element.

2021-05-31 15:56 UTC, HFaaaaa commented
PTAL

2021-05-31 16:20 UTC, Jogo27 requested changes
You still has to remove the left margin of buttons, and to take the following two remarks into account.

2021-05-31 16:20 UTC, Jogo27 commented on app/src/styles.sass
> +      @include userbox
You don't need to repeat that here. buttons in element with formactions class have already included userbox. Moreover, it results in errors, like the font size which is smaller on narrow screens. Just remove this line.

2021-05-31 16:20 UTC, Jogo27 commented on app/src/styles.sass
> +    margin-left: 0
Useless. The left margin already is zero for formactions.

2021-05-31 16:39 UTC, HFaaaaa commented
PTAL

2021-05-31 17:02 UTC, Jogo27 approved these changes

2021-05-31 17:03 UTC, merged